// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHkXps4DmR5Tnnz00m7V1BqhL2xv_0BI',
    appId: '1:559563343307:web:b477be195045a03960624e',
    messagingSenderId: '559563343307',
    projectId: 'chattify-3d4a4',
    authDomain: 'chattify-3d4a4.firebaseapp.com',
    storageBucket: 'chattify-3d4a4.appspot.com',
    measurementId: 'G-2Y3N6QPGNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQmcZ4XdYZ3TUMLOnkoXLVgfBrALN3z0',
    appId: '1:559563343307:android:135b3c7475c5d6f260624e',
    messagingSenderId: '559563343307',
    projectId: 'chattify-3d4a4',
    storageBucket: 'chattify-3d4a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7qqVWfZBTKcLkzRLGjxO8juI4rwcwVGE',
    appId: '1:559563343307:ios:a24273774151c90660624e',
    messagingSenderId: '559563343307',
    projectId: 'chattify-3d4a4',
    storageBucket: 'chattify-3d4a4.appspot.com',
    iosClientId: '559563343307-6ueekan228c4ffcspnk5vf78pp6nnu60.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7qqVWfZBTKcLkzRLGjxO8juI4rwcwVGE',
    appId: '1:559563343307:ios:2bb4114bac564c5e60624e',
    messagingSenderId: '559563343307',
    projectId: 'chattify-3d4a4',
    storageBucket: 'chattify-3d4a4.appspot.com',
    iosClientId: '559563343307-ol5p58bdho33uv8o9pbiuk18pd0oun8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattify.RunnerTests',
  );
}
