// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFQ7lAlsm7p3lHWBJ4INvPIrpUGM7-bE',
    appId: '1:170248401704:web:918c73d318b779dab6961d',
    messagingSenderId: '170248401704',
    projectId: 'chattify2',
    authDomain: 'chattify2.firebaseapp.com',
    storageBucket: 'chattify2.appspot.com',
    measurementId: 'G-8KZV29PQR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIXuHARcso0_MKLRx2rUhdfZoca-M8id8',
    appId: '1:170248401704:android:0086df04d73b34fbb6961d',
    messagingSenderId: '170248401704',
    projectId: 'chattify2',
    storageBucket: 'chattify2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAscBvumlLpIlOpVLI4UxAQyY28a8uyjTE',
    appId: '1:170248401704:ios:fc7450392af4b560b6961d',
    messagingSenderId: '170248401704',
    projectId: 'chattify2',
    storageBucket: 'chattify2.appspot.com',
    iosClientId: '170248401704-8oattbdkbc6grp3b1i1ndaccup7nee7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattify',
  );
}
